In [15]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pylab as plt
from matplotlib.pyplot import imread
%matplotlib inline

In [16]:
df = pd.read_csv('train.txt',header=None)

In [17]:
df.columns = ['subject-id','activity-code','timestamp','x','y','z']

In [18]:
df.head()

subject-id activity-code       timestamp         x          y         z
0          33      Upstairs  49591302292000  0.381370  13.865514  1.225831
1          33      Upstairs  49591412308000 -2.111154  10.147159  0.885323
2          33      Upstairs  49591522323000  0.381370   5.366417  0.653777
3          33      Upstairs  49591632309000  1.184970   4.018003  3.595772
4          33      Upstairs  49591742294000  1.334794  17.011814  4.058864

In [19]:
from sklearn.preprocessing import LabelEncoder 

In [20]:
le = LabelEncoder() 
df['activity-code']= le.fit_transform(df['activity-code'])

In [21]:
df.head()

subject-id  activity-code       timestamp         x          y         z
0          33              4  49591302292000  0.381370  13.865514  1.225831
1          33              4  49591412308000 -2.111154  10.147159  0.885323
2          33              4  49591522323000  0.381370   5.366417  0.653777
3          33              4  49591632309000  1.184970   4.018003  3.595772
4          33              4  49591742294000  1.334794  17.011814  4.058864

In [22]:
df.dropna(axis=0, inplace = True)

In [23]:
df.head()

subject-id  activity-code       timestamp         x          y         z
0          33              4  49591302292000  0.381370  13.865514  1.225831
1          33              4  49591412308000 -2.111154  10.147159  0.885323
2          33              4  49591522323000  0.381370   5.366417  0.653777
3          33              4  49591632309000  1.184970   4.018003  3.595772
4          33              4  49591742294000  1.334794  17.011814  4.058864

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1098080 entries, 0 to 1098080
Data columns (total 6 columns):
subject-id       1098080 non-null int64
activity-code    1098080 non-null int32
timestamp        1098080 non-null int64
x                1098080 non-null float64
y                1098080 non-null float64
z                1098080 non-null float64
dtypes: float64(3), int32(1), int64(2)
memory usage: 54.5 MB


In [8]:
# sns.pairplot(df,hue='activity-code',palette='Set1')

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X = df.drop('activity-code',axis=1)
y = df['activity-code']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
dtree = DecisionTreeClassifier()

In [30]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [31]:
##Prediction

predictions = dtree.predict(X_test)

In [32]:
from sklearn.metrics import classification_report,confusion_matrix

In [33]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98     29810
           1       0.99      1.00      0.99    102699
           2       1.00      1.00      1.00     18147
           3       1.00      1.00      1.00     14478
           4       0.98      0.98      0.98     36846
           5       1.00      1.00      1.00    127444

    accuracy                           0.99    329424
   macro avg       0.99      0.99      0.99    329424
weighted avg       0.99      0.99      0.99    329424



In [36]:
print(confusion_matrix(y_test,predictions))

[[ 29166    120      4      5    498     17]
 [    69 102223     14      1     90    302]
 [     2     14  18119      4      2      6]
 [     4      0      1  14461      7      5]
 [   438    180      0      3  36198     27]
 [    24    471      7      7     25 126910]]


# Random Forest


In [40]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [41]:
rfc_pred = rfc.predict(X_test)

In [42]:
print(confusion_matrix(y_test,rfc_pred))

[[ 28731    142      0      0    923     14]
 [     2 102581      1      0      5    110]
 [     1      5  18139      0      0      2]
 [     3      1      0  14471      1      2]
 [  1122    187      0      0  35518     19]
 [     0    484      0      0      7 126953]]


In [43]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96     29810
           1       0.99      1.00      1.00    102699
           2       1.00      1.00      1.00     18147
           3       1.00      1.00      1.00     14478
           4       0.97      0.96      0.97     36846
           5       1.00      1.00      1.00    127444

    accuracy                           0.99    329424
   macro avg       0.99      0.99      0.99    329424
weighted avg       0.99      0.99      0.99    329424



# KNN 

In [46]:
df.head()

subject-id  activity-code       timestamp         x          y         z
0          33              4  49591302292000  0.381370  13.865514  1.225831
1          33              4  49591412308000 -2.111154  10.147159  0.885323
2          33              4  49591522323000  0.381370   5.366417  0.653777
3          33              4  49591632309000  1.184970   4.018003  3.595772
4          33              4  49591742294000  1.334794  17.011814  4.058864

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [59]:
scaler.fit(df.drop('activity-code',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [60]:
scaled_features = scaler.transform(df.drop('activity-code',axis=1))

In [67]:
df_feat = pd.DataFrame(scaled_features,columns=df.columns[:1:2:])snisn
df_feat.head()

SyntaxError: invalid syntax (<ipython-input-67-5cdcfe4f6e3f>, line 1)